#!/bin/bash
#   
#     Collector is a tool for obtaining bioactivity data from the Open PHACTS platform.
#     Copyright (C) 2013 UPF
#     Contributed by Manuel Pastor(manuel.pastor@upf.edu) and Oriol L. Massaguer(olopez@imim.es). 
# 
#    This file is part of Collector.
#
#    Collector is free software: you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation, either version 3 of the License, or
#    (at your option) any later version.
#
#    Collector is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with Collector.  If not, see <http://www.gnu.org/licenses/>.   
# 

COLLECTOR_INSTALL=$(dirname $0)
source $COLLECTOR_INSTALL/environment

if [ -f "$COLLECTOR_HOME/collector" ]
then
	echo "COLLECTOR_HOME passed"
else
	echo "Collector not found. Check COLLECTOR_HOME in environment file"
	exit 1
fi

if [ -f "$JAVA_HOME/bin/java" ]
then
	echo "JAVA_HOME passed"
else
	echo "Java not found. Check JAVA_HOME in environment file"
	exit 1
fi

if [ -f "$PG_HOME/bin/psql" ]
then
	echo "PG_HOME passed"
else
	echo "PostgreSQL not found in $PG_HOME. Check PG_HOME in environment file"
	exit 1
fi

$PG_HOME/bin/psql -q -l

if [ $? -eq 0 ]
then
	echo "PostgreSQL connection passed"
else
	echo "PostgreSQL connection failed. Check database connection parameters in environment file"
	exit 1
fi

echo
echo
